# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor, QIcon
import regi_db

class Ui_reGI(object):
    def setupUi(self, reGI):
        reGI.setObjectName("reGI")
        reGI.resize(1500, 950)
        reGI.setAutoFillBackground(True)
        reGI.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(reGI)
        self.centralWidget.setAutoFillBackground(True)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1500, 921))
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pag_0 = QtWidgets.QWidget()
        self.pag_0.setObjectName("pag_0")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pag_0)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 1501, 921))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_nuovo_prev = QtWidgets.QPushButton(self.groupBox)
        self.btn_nuovo_prev.setEnabled(True)
        self.btn_nuovo_prev.setGeometry(QtCore.QRect(30, 120, 175, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_nuovo_prev.setFont(font)
        self.btn_nuovo_prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nuovo_prev.setObjectName("btn_nuovo_prev")
        self.btn_apri_prev = QtWidgets.QPushButton(self.groupBox)
        self.btn_apri_prev.setGeometry(QtCore.QRect(30, 170, 175, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_apri_prev.setFont(font)
        self.btn_apri_prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_apri_prev.setObjectName("btn_apri_prev")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(30, 330, 250, 250))
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_view_anagrafica = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_view_anagrafica.setGeometry(QtCore.QRect(30, 120, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_view_anagrafica.setFont(font)
        self.btn_view_anagrafica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_view_anagrafica.setObjectName("btn_view_anagrafica")
        self.btn_agg_cliente_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_agg_cliente_2.setGeometry(QtCore.QRect(30, 170, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_agg_cliente_2.setFont(font)
        self.btn_agg_cliente_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agg_cliente_2.setObjectName("btn_agg_cliente_2")
        self.btn_edit_cliente = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_edit_cliente.setGeometry(QtCore.QRect(30, 220, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_edit_cliente.setFont(font)
        self.btn_edit_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_edit_cliente.setObjectName("btn_edit_cliente")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_view_modelli = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_view_modelli.setGeometry(QtCore.QRect(30, 120, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_view_modelli.setFont(font)
        self.btn_view_modelli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_view_modelli.setObjectName("btn_view_modelli")
        self.btn_agg_modello = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_agg_modello.setGeometry(QtCore.QRect(30, 170, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_agg_modello.setFont(font)
        self.btn_agg_modello.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agg_modello.setObjectName("btn_agg_modello")
        self.btn_edit_modello = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_edit_modello.setGeometry(QtCore.QRect(30, 220, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_edit_modello.setFont(font)
        self.btn_edit_modello.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_edit_modello.setObjectName("btn_edit_modello")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.pag_0)
        self.pag_1 = QtWidgets.QWidget()
        self.pag_1.setObjectName("pag_1")
        self.tab_clienti = QtWidgets.QTableWidget(self.pag_1)
        self.tab_clienti.setGeometry(QtCore.QRect(10, 80, 1480, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_clienti.setFont(font)
        self.tab_clienti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_clienti.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tab_clienti.setAlternatingRowColors(True)
        self.tab_clienti.setGridStyle(QtCore.Qt.DotLine)
        self.tab_clienti.setObjectName("tab_clienti")
        self.tab_clienti.setColumnCount(8)
        self.tab_clienti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_clienti.setHorizontalHeaderItem(7, item)
        self.tab_clienti.horizontalHeader().setCascadingSectionResizes(False)
        self.tab_clienti.horizontalHeader().setDefaultSectionSize(110)
        self.tab_clienti.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.pag_1)
        self.label_2.setGeometry(QtCore.QRect(15, 30, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.pag_1)
        self.frame_2.setGeometry(QtCore.QRect(10, 550, 530, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_canc_cliente = QtWidgets.QPushButton(self.frame_2)
        self.btn_canc_cliente.setEnabled(True)
        self.btn_canc_cliente.setGeometry(QtCore.QRect(370, 10, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_canc_cliente.setFont(font)
        self.btn_canc_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_canc_cliente.setObjectName("btn_canc_cliente")
        self.btn_scegli_cliente = QtWidgets.QPushButton(self.frame_2)
        self.btn_scegli_cliente.setGeometry(QtCore.QRect(10, 10, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_scegli_cliente.setFont(font)
        self.btn_scegli_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_scegli_cliente.setObjectName("btn_scegli_cliente")
        self.btn_agg_cliente = QtWidgets.QPushButton(self.frame_2)
        self.btn_agg_cliente.setEnabled(True)
        self.btn_agg_cliente.setGeometry(QtCore.QRect(190, 10, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_agg_cliente.setFont(font)
        self.btn_agg_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agg_cliente.setObjectName("btn_agg_cliente")
        self.stackedWidget.addWidget(self.pag_1)
        self.pag_2 = QtWidgets.QWidget()
        self.pag_2.setObjectName("pag_2")
        self.tab_dettaglio_totale = QtWidgets.QTabWidget(self.pag_2)
        self.tab_dettaglio_totale.setGeometry(QtCore.QRect(10, 160, 1481, 751))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tab_dettaglio_totale.setFont(font)
        self.tab_dettaglio_totale.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_dettaglio_totale.setIconSize(QtCore.QSize(16, 20))
        self.tab_dettaglio_totale.setObjectName("tab_dettaglio_totale")
        self.scheda_dettaglio = QtWidgets.QWidget()
        self.scheda_dettaglio.setObjectName("scheda_dettaglio")
        self.list_serr = QtWidgets.QListWidget(self.scheda_dettaglio)
        self.list_serr.setGeometry(QtCore.QRect(10, 90, 305, 621))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.list_serr.setFont(font)
        self.list_serr.setAlternatingRowColors(True)
        self.list_serr.setObjectName("list_serr")
        self.label_23 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_23.setGeometry(QtCore.QRect(355, 15, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.edit_cod_prog = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog.setGeometry(QtCore.QRect(470, 10, 90, 25))
        self.edit_cod_prog.setText("")
        self.edit_cod_prog.setPlaceholderText("")
        self.edit_cod_prog.setObjectName("edit_cod_prog")
        self.label_24 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_24.setGeometry(QtCore.QRect(355, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.edit_note_descr = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_note_descr.setGeometry(QtCore.QRect(440, 120, 415, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.edit_note_descr.setFont(font)
        self.edit_note_descr.setClearButtonEnabled(True)
        self.edit_note_descr.setObjectName("edit_note_descr")
        self.label_25 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_25.setGeometry(QtCore.QRect(360, 125, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.toolButton_9 = QtWidgets.QToolButton(self.scheda_dettaglio)
        self.toolButton_9.setGeometry(QtCore.QRect(565, 10, 25, 25))
        self.toolButton_9.setObjectName("toolButton_9")
        self.btn_nuovo_serr = QtWidgets.QPushButton(self.scheda_dettaglio)
        self.btn_nuovo_serr.setGeometry(QtCore.QRect(10, 10, 75, 61))
        self.btn_nuovo_serr.setObjectName("btn_nuovo_serr")
        self.btn_dupl_serr = QtWidgets.QPushButton(self.scheda_dettaglio)
        self.btn_dupl_serr.setGeometry(QtCore.QRect(110, 10, 91, 61))
        self.btn_dupl_serr.setObjectName("btn_dupl_serr")
        self.btn_canc_serr = QtWidgets.QPushButton(self.scheda_dettaglio)
        self.btn_canc_serr.setGeometry(QtCore.QRect(225, 10, 91, 61))
        self.btn_canc_serr.setObjectName("btn_canc_serr")
        self.line_5 = QtWidgets.QFrame(self.scheda_dettaglio)
        self.line_5.setGeometry(QtCore.QRect(325, 0, 20, 721))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.edit_descr = QtWidgets.QTextEdit(self.scheda_dettaglio)
        self.edit_descr.setGeometry(QtCore.QRect(439, 45, 391, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit_descr.setFont(font)
        self.edit_descr.setObjectName("edit_descr")
        self.graphicsView = QtWidgets.QGraphicsView(self.scheda_dettaglio)
        self.graphicsView.setGeometry(QtCore.QRect(355, 530, 180, 180))
        self.graphicsView.setObjectName("graphicsView")
        self.label_26 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_26.setEnabled(False)
        self.label_26.setGeometry(QtCore.QRect(740, 530, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scheda_dettaglio)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QtCore.QRect(740, 580, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.scheda_dettaglio)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(740, 555, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.scheda_dettaglio)
        self.graphicsView_2.setEnabled(False)
        self.graphicsView_2.setGeometry(QtCore.QRect(540, 530, 180, 180))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_27 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_27.setGeometry(QtCore.QRect(620, 15, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.edit_cod_pos = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_pos.setGeometry(QtCore.QRect(670, 10, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.edit_cod_pos.setFont(font)
        self.edit_cod_pos.setText("")
        self.edit_cod_pos.setPlaceholderText("")
        self.edit_cod_pos.setClearButtonEnabled(True)
        self.edit_cod_pos.setObjectName("edit_cod_pos")
        self.combo_materiale = QtWidgets.QComboBox(self.scheda_dettaglio)
        self.combo_materiale.setGeometry(QtCore.QRect(989, 345, 141, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_materiale.setFont(font)
        self.combo_materiale.setObjectName("combo_materiale")
        self.combo_materiale.addItem("")
        self.combo_materiale.addItem("")
        self.label_28 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_28.setGeometry(QtCore.QRect(900, 350, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.combo_vernice = QtWidgets.QComboBox(self.scheda_dettaglio)
        self.combo_vernice.setGeometry(QtCore.QRect(989, 385, 141, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_vernice.setFont(font)
        self.combo_vernice.setObjectName("combo_vernice")
        self.label_29 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_29.setGeometry(QtCore.QRect(900, 390, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.tree_progetti = QtWidgets.QTreeWidget(self.scheda_dettaglio)
        self.tree_progetti.setGeometry(QtCore.QRect(355, 160, 500, 360))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tree_progetti.setFont(font)
        self.tree_progetti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tree_progetti.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_progetti.setAlternatingRowColors(False)
        self.tree_progetti.setAnimated(True)
        self.tree_progetti.setObjectName("tree_progetti")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tree_progetti.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tree_progetti.headerItem().setFont(1, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_progetti)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_progetti)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_progetti)
        self.tree_progetti.header().setCascadingSectionResizes(True)
        self.tree_progetti.header().setDefaultSectionSize(300)
        self.tree_progetti.header().setStretchLastSection(True)
        self.combo_variante3 = QtWidgets.QComboBox(self.scheda_dettaglio)
        self.combo_variante3.setEnabled(False)
        self.combo_variante3.setGeometry(QtCore.QRect(965, 425, 165, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_variante3.setFont(font)
        self.combo_variante3.setObjectName("combo_variante3")
        self.label_30 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_30.setEnabled(False)
        self.label_30.setGeometry(QtCore.QRect(900, 430, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.line_6 = QtWidgets.QFrame(self.scheda_dettaglio)
        self.line_6.setGeometry(QtCore.QRect(865, 0, 20, 721))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.scheda_dettaglio)
        self.line_7.setGeometry(QtCore.QRect(1150, 0, 20, 721))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.spin_l = QtWidgets.QSpinBox(self.scheda_dettaglio)
        self.spin_l.setGeometry(QtCore.QRect(979, 65, 141, 25))
        self.spin_l.setPrefix("")
        self.spin_l.setMaximum(5000)
        self.spin_l.setSingleStep(10)
        self.spin_l.setObjectName("spin_l")
        self.label_9 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_9.setGeometry(QtCore.QRect(900, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spin_h = QtWidgets.QSpinBox(self.scheda_dettaglio)
        self.spin_h.setGeometry(QtCore.QRect(979, 105, 141, 25))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.spin_h.setFont(font)
        self.spin_h.setPrefix("")
        self.spin_h.setMaximum(5000)
        self.spin_h.setSingleStep(10)
        self.spin_h.setObjectName("spin_h")
        self.label_10 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_10.setGeometry(QtCore.QRect(900, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spin_s = QtWidgets.QSpinBox(self.scheda_dettaglio)
        self.spin_s.setEnabled(False)
        self.spin_s.setGeometry(QtCore.QRect(979, 145, 141, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.spin_s.setFont(font)
        self.spin_s.setPrefix("")
        self.spin_s.setMaximum(10000)
        self.spin_s.setSingleStep(10)
        self.spin_s.setObjectName("spin_s")
        self.label_11 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(900, 150, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_31 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_31.setGeometry(QtCore.QRect(900, 465, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.edit_note_varianti = QtWidgets.QTextEdit(self.scheda_dettaglio)
        self.edit_note_varianti.setGeometry(QtCore.QRect(900, 485, 230, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.edit_note_varianti.setFont(font)
        self.edit_note_varianti.setObjectName("edit_note_varianti")
        self.spin_pezzi = QtWidgets.QSpinBox(self.scheda_dettaglio)
        self.spin_pezzi.setGeometry(QtCore.QRect(979, 10, 141, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_pezzi.setFont(font)
        self.spin_pezzi.setReadOnly(False)
        self.spin_pezzi.setPrefix("")
        self.spin_pezzi.setMinimum(1)
        self.spin_pezzi.setMaximum(10)
        self.spin_pezzi.setSingleStep(1)
        self.spin_pezzi.setObjectName("spin_pezzi")
        self.label_12 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_12.setGeometry(QtCore.QRect(900, 15, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_deduci_num_prev_2 = QtWidgets.QToolButton(self.scheda_dettaglio)
        self.btn_deduci_num_prev_2.setEnabled(True)
        self.btn_deduci_num_prev_2.setGeometry(QtCore.QRect(835, 70, 25, 25))
        self.btn_deduci_num_prev_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/document_arrow_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_deduci_num_prev_2.setIcon(icon)
        self.btn_deduci_num_prev_2.setObjectName("btn_deduci_num_prev_2")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.lineEdit_10.setGeometry(QtCore.QRect(1260, 10, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setFrame(False)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_32 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_32.setGeometry(QtCore.QRect(1200, 15, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_33.setGeometry(QtCore.QRect(1200, 55, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.lineEdit_11.setGeometry(QtCore.QRect(1260, 50, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setFrame(False)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.edit_cod_prog_2 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog_2.setGeometry(QtCore.QRect(1325, 130, 90, 25))
        self.edit_cod_prog_2.setText("")
        self.edit_cod_prog_2.setReadOnly(True)
        self.edit_cod_prog_2.setPlaceholderText("")
        self.edit_cod_prog_2.setObjectName("edit_cod_prog_2")
        self.label_34 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_34.setGeometry(QtCore.QRect(1195, 135, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.edit_cod_prog_3 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog_3.setGeometry(QtCore.QRect(1325, 190, 90, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_cod_prog_3.setFont(font)
        self.edit_cod_prog_3.setText("")
        self.edit_cod_prog_3.setReadOnly(True)
        self.edit_cod_prog_3.setPlaceholderText("")
        self.edit_cod_prog_3.setObjectName("edit_cod_prog_3")
        self.label_13 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_13.setGeometry(QtCore.QRect(1421, 135, 16, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.lineEdit.setGeometry(QtCore.QRect(1435, 130, 25, 25))
        self.lineEdit.setFrame(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.edit_cod_prog_4 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog_4.setGeometry(QtCore.QRect(1325, 220, 90, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_cod_prog_4.setFont(font)
        self.edit_cod_prog_4.setText("")
        self.edit_cod_prog_4.setReadOnly(True)
        self.edit_cod_prog_4.setPlaceholderText("")
        self.edit_cod_prog_4.setObjectName("edit_cod_prog_4")
        self.radioButton = QtWidgets.QRadioButton(self.scheda_dettaglio)
        self.radioButton.setGeometry(QtCore.QRect(1195, 195, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.scheda_dettaglio)
        self.radioButton_2.setGeometry(QtCore.QRect(1195, 225, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.edit_cod_prog_5 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog_5.setGeometry(QtCore.QRect(1305, 340, 110, 25))
        self.edit_cod_prog_5.setText("")
        self.edit_cod_prog_5.setReadOnly(True)
        self.edit_cod_prog_5.setPlaceholderText("")
        self.edit_cod_prog_5.setObjectName("edit_cod_prog_5")
        self.label_35 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_35.setGeometry(QtCore.QRect(1195, 345, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.scheda_dettaglio)
        self.label_37.setGeometry(QtCore.QRect(1195, 285, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.edit_cod_prog_6 = QtWidgets.QLineEdit(self.scheda_dettaglio)
        self.edit_cod_prog_6.setGeometry(QtCore.QRect(1325, 280, 90, 25))
        self.edit_cod_prog_6.setText("")
        self.edit_cod_prog_6.setReadOnly(True)
        self.edit_cod_prog_6.setPlaceholderText("")
        self.edit_cod_prog_6.setObjectName("edit_cod_prog_6")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/dettaglio_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_dettaglio_totale.addTab(self.scheda_dettaglio, icon1, "")
        self.scheda_totale = QtWidgets.QWidget()
        self.scheda_totale.setObjectName("scheda_totale")
        self.label_36 = QtWidgets.QLabel(self.scheda_totale)
        self.label_36.setGeometry(QtCore.QRect(10, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.tableWidget = QtWidgets.QTableWidget(self.scheda_totale)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 400, 660))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(141)
        self.tableWidget.verticalHeader().setVisible(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/total_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_dettaglio_totale.addTab(self.scheda_totale, icon2, "")
        self.frame = QtWidgets.QFrame(self.pag_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1480, 130))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.num_prev_edit = QtWidgets.QLineEdit(self.frame)
        self.num_prev_edit.setGeometry(QtCore.QRect(10, 30, 113, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_prev_edit.setFont(font)
        self.num_prev_edit.setText("")
        self.num_prev_edit.setObjectName("num_prev_edit")
        self.btn_deduci_num_prev = QtWidgets.QToolButton(self.frame)
        self.btn_deduci_num_prev.setEnabled(True)
        self.btn_deduci_num_prev.setGeometry(QtCore.QRect(125, 30, 25, 25))
        self.btn_deduci_num_prev.setText("")
        self.btn_deduci_num_prev.setIcon(icon)
        self.btn_deduci_num_prev.setObjectName("btn_deduci_num_prev")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(170, 10, 31, 16))
        self.label_5.setObjectName("label_5")
        self.data_prev_edit = QtWidgets.QDateEdit(self.frame)
        self.data_prev_edit.setGeometry(QtCore.QRect(170, 30, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.data_prev_edit.setFont(font)
        self.data_prev_edit.setObjectName("data_prev_edit")
        self.btn_deduci_data_prev = QtWidgets.QToolButton(self.frame)
        self.btn_deduci_data_prev.setEnabled(True)
        self.btn_deduci_data_prev.setGeometry(QtCore.QRect(282, 30, 25, 25))
        self.btn_deduci_data_prev.setText("")
        self.btn_deduci_data_prev.setIcon(icon)
        self.btn_deduci_data_prev.setObjectName("btn_deduci_data_prev")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(740, 0, 16, 131))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(760, 10, 111, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(760, 30, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(975, 10, 51, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(975, 30, 240, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(1230, 30, 240, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(1230, 10, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(760, 90, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setFrame(False)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(760, 70, 111, 16))
        self.label_14.setObjectName("label_14")
        self.testo_in_edit = QtWidgets.QLineEdit(self.frame)
        self.testo_in_edit.setGeometry(QtCore.QRect(10, 90, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testo_in_edit.setFont(font)
        self.testo_in_edit.setObjectName("testo_in_edit")
        self.btn_scegli_testo_in = QtWidgets.QToolButton(self.frame)
        self.btn_scegli_testo_in.setGeometry(QtCore.QRect(162, 90, 25, 25))
        self.btn_scegli_testo_in.setObjectName("btn_scegli_testo_in")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.testo_out_edit = QtWidgets.QLineEdit(self.frame)
        self.testo_out_edit.setGeometry(QtCore.QRect(245, 90, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testo_out_edit.setFont(font)
        self.testo_out_edit.setObjectName("testo_out_edit")
        self.btn_scegli_testo_out = QtWidgets.QToolButton(self.frame)
        self.btn_scegli_testo_out.setGeometry(QtCore.QRect(396, 90, 25, 25))
        self.btn_scegli_testo_out.setObjectName("btn_scegli_testo_out")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(245, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_12.setGeometry(QtCore.QRect(975, 90, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setText("")
        self.lineEdit_12.setFrame(False)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(975, 70, 111, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_13.setGeometry(QtCore.QRect(1135, 90, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setText("")
        self.lineEdit_13.setFrame(False)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(1135, 70, 111, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(1300, 70, 111, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(1300, 90, 170, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setText("")
        self.lineEdit_14.setFrame(False)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_15.setGeometry(QtCore.QRect(330, 30, 153, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setText("")
        self.lineEdit_15.setFrame(False)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(330, 10, 81, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_16.setGeometry(QtCore.QRect(495, 30, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setFrame(False)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(495, 10, 101, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_17.setGeometry(QtCore.QRect(610, 30, 125, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setText("")
        self.lineEdit_17.setFrame(False)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(610, 10, 91, 16))
        self.label_22.setObjectName("label_22")
        self.btn_deduci_num_prev_3 = QtWidgets.QToolButton(self.frame)
        self.btn_deduci_num_prev_3.setEnabled(True)
        self.btn_deduci_num_prev_3.setGeometry(QtCore.QRect(190, 90, 25, 25))
        self.btn_deduci_num_prev_3.setText("")
        self.btn_deduci_num_prev_3.setIcon(icon)
        self.btn_deduci_num_prev_3.setObjectName("btn_deduci_num_prev_3")
        self.btn_deduci_num_prev_4 = QtWidgets.QToolButton(self.frame)
        self.btn_deduci_num_prev_4.setEnabled(True)
        self.btn_deduci_num_prev_4.setGeometry(QtCore.QRect(425, 90, 25, 25))
        self.btn_deduci_num_prev_4.setText("")
        self.btn_deduci_num_prev_4.setIcon(icon)
        self.btn_deduci_num_prev_4.setObjectName("btn_deduci_num_prev_4")
        self.line_2 = QtWidgets.QFrame(self.pag_2)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 1481, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.stackedWidget.addWidget(self.pag_2)
        self.pag_3 = QtWidgets.QWidget()
        self.pag_3.setObjectName("pag_3")
        self.stackedWidget.addWidget(self.pag_3)
        reGI.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(reGI)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 21))
        self.menubar.setObjectName("menubar")
        self.menuNuovo = QtWidgets.QMenu(self.menubar)
        self.menuNuovo.setObjectName("menuNuovo")
        self.menuRecenti = QtWidgets.QMenu(self.menuNuovo)
        self.menuRecenti.setObjectName("menuRecenti")
        self.menuNuovo_2 = QtWidgets.QMenu(self.menuNuovo)
        self.menuNuovo_2.setObjectName("menuNuovo_2")
        self.menuInserisci = QtWidgets.QMenu(self.menubar)
        self.menuInserisci.setObjectName("menuInserisci")
        self.menuVista = QtWidgets.QMenu(self.menubar)
        self.menuVista.setObjectName("menuVista")
        self.menuSeleziona_stile = QtWidgets.QMenu(self.menuVista)
        self.menuSeleziona_stile.setObjectName("menuSeleziona_stile")
        self.menuAnteprima = QtWidgets.QMenu(self.menubar)
        self.menuAnteprima.setObjectName("menuAnteprima")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        reGI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(reGI)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        reGI.setStatusBar(self.statusbar)
        self.actionVersione = QtWidgets.QAction(reGI)
        self.actionVersione.setObjectName("actionVersione")
        self.actionVerifica_aggiornamenti = QtWidgets.QAction(reGI)
        self.actionVerifica_aggiornamenti.setObjectName("actionVerifica_aggiornamenti")
        self.actionApri = QtWidgets.QAction(reGI)
        self.actionApri.setObjectName("actionApri")
        self.actionRecente_1 = QtWidgets.QAction(reGI)
        self.actionRecente_1.setObjectName("actionRecente_1")
        self.actionRecente_2 = QtWidgets.QAction(reGI)
        self.actionRecente_2.setObjectName("actionRecente_2")
        self.actionDa_zero = QtWidgets.QAction(reGI)
        self.actionDa_zero.setObjectName("actionDa_zero")
        self.actionDa_precompilato = QtWidgets.QAction(reGI)
        self.actionDa_precompilato.setEnabled(False)
        self.actionDa_precompilato.setObjectName("actionDa_precompilato")
        self.actionInfisso = QtWidgets.QAction(reGI)
        self.actionInfisso.setObjectName("actionInfisso")
        self.actionVisualizza_anteprima_di_stampa = QtWidgets.QAction(reGI)
        self.actionVisualizza_anteprima_di_stampa.setObjectName("actionVisualizza_anteprima_di_stampa")
        self.actionDefault = QtWidgets.QAction(reGI)
        self.actionDefault.setObjectName("actionDefault")
        self.actionFusion = QtWidgets.QAction(reGI)
        self.actionFusion.setObjectName("actionFusion")
        self.actionWindows = QtWidgets.QAction(reGI)
        self.actionWindows.setObjectName("actionWindows")
        self.actionWindows_Vista = QtWidgets.QAction(reGI)
        self.actionWindows_Vista.setObjectName("actionWindows_Vista")
        self.actionSchermata_iniziale = QtWidgets.QAction(reGI)
        self.actionSchermata_iniziale.setCheckable(False)
        self.actionSchermata_iniziale.setObjectName("actionSchermata_iniziale")
        self.actionAnagrafica_clienti = QtWidgets.QAction(reGI)
        self.actionAnagrafica_clienti.setObjectName("actionAnagrafica_clienti")
        self.actionLista_progetti = QtWidgets.QAction(reGI)
        self.actionLista_progetti.setObjectName("actionLista_progetti")
        self.actionCliente = QtWidgets.QAction(reGI)
        self.actionCliente.setObjectName("actionCliente")
        self.actionProgetto = QtWidgets.QAction(reGI)
        self.actionProgetto.setObjectName("actionProgetto")
        self.menuRecenti.addAction(self.actionRecente_1)
        self.menuRecenti.addAction(self.actionRecente_2)
        self.menuNuovo_2.addAction(self.actionDa_zero)
        self.menuNuovo_2.addAction(self.actionDa_precompilato)
        self.menuNuovo_2.addAction(self.actionCliente)
        self.menuNuovo_2.addAction(self.actionProgetto)
        self.menuNuovo.addAction(self.actionSchermata_iniziale)
        self.menuNuovo.addAction(self.actionAnagrafica_clienti)
        self.menuNuovo.addAction(self.actionLista_progetti)
        self.menuNuovo.addSeparator()
        self.menuNuovo.addAction(self.menuNuovo_2.menuAction())
        self.menuNuovo.addAction(self.actionApri)
        self.menuNuovo.addAction(self.menuRecenti.menuAction())
        self.menuInserisci.addAction(self.actionInfisso)
        self.menuSeleziona_stile.addAction(self.actionDefault)
        self.menuSeleziona_stile.addAction(self.actionFusion)
        self.menuSeleziona_stile.addAction(self.actionWindows)
        self.menuSeleziona_stile.addAction(self.actionWindows_Vista)
        self.menuVista.addAction(self.menuSeleziona_stile.menuAction())
        self.menuAnteprima.addAction(self.actionVisualizza_anteprima_di_stampa)
        self.menuInfo.addAction(self.actionVersione)
        self.menuInfo.addAction(self.actionVerifica_aggiornamenti)
        self.menubar.addAction(self.menuNuovo.menuAction())
        self.menubar.addAction(self.menuInserisci.menuAction())
        self.menubar.addAction(self.menuVista.menuAction())
        self.menubar.addAction(self.menuAnteprima.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.retranslateUi(reGI)
##################################################################################################
        
        self.stackedWidget.setCurrentIndex(0)
        self.tab_dettaglio_totale.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(reGI)
        palette_preventivi = QtGui.QPalette()
        palette_preventivi.setColor(QtGui.QPalette.Background, QColor("#ccfff0"))
        self.groupBox.setPalette(palette_preventivi)
        self.tab_dettaglio_totale.setPalette(palette_preventivi)
        palette_clienti = QtGui.QPalette()
        palette_clienti.setColor(QtGui.QPalette.Background, QColor("#ccf0ff"))
        self.groupBox_2.setPalette(palette_clienti)
        self.pag_1.setPalette(palette_clienti)
        palette_progetti = QtGui.QPalette()
        palette_progetti.setColor(QtGui.QPalette.Background, QColor("#f0ffcc"))
        self.groupBox_3.setPalette(palette_progetti)
        self.tree_progetti.setPalette(palette_progetti)
        self.btn_nuovo_prev.clicked.connect(self.view_db_clienti)
        self.btn_view_anagrafica.clicked.connect(self.view_anagrafica)
        self.btn_scegli_cliente.clicked.connect(self.scegli_cliente)

        self.current_cliente = {}
        self.current_prev = {}

    def view_db_clienti(self):
        self.stackedWidget.setCurrentIndex(1)
        query = regi_db.Cliente.select().dicts()
        print(query)
        for num_riga, cliente in enumerate(query):
            self.tab_clienti.insertRow(num_riga)
            for num_colonna, dato in enumerate(cliente.values()):
                print(num_riga, num_colonna, dato)
                if num_colonna == 0:
                    continue # evita la colonna id del db
                if dato == None:
                    dato = "Nessuno"
                self.tab_clienti.setItem(num_riga, num_colonna-1, QtWidgets.QTableWidgetItem(str(dato)))
    def view_anagrafica(self):
        self.view_db_clienti()
        self.label_2.enabled = False
        self.btn_scegli_cliente.enabled = False
    def scegli_cliente(self):
        for self.current_cliente
    def crea_prev(self):
        pass
        # row = self.products_table.currentRow()
        # currentproductid = (self.products_table.item(row, 0).text() )
        # query = session.query(Product).filter(Product.product_id==str(currentproductid)).first()
        # session.delete(query)
        # session.commit()
        # self.products_table.removeRow(row)

##################################################################################################
    def retranslateUi(self, reGI):
        _translate = QtCore.QCoreApplication.translate
        reGI.setWindowTitle(_translate("reGI", "MainWindow"))
        self.groupBox.setTitle(_translate("reGI", "Preventivi"))
        self.label_3.setText(_translate("reGI", "Inizia"))
        self.label_4.setText(_translate("reGI", "Recenti"))
        self.btn_nuovo_prev.setText(_translate("reGI", "Nuovo preventivo..."))
        self.btn_apri_prev.setText(_translate("reGI", "Apri preventivo..."))
        self.groupBox_2.setTitle(_translate("reGI", "Clienti"))
        self.btn_view_anagrafica.setText(_translate("reGI", "Visualizza anagrafica clienti"))
        self.btn_agg_cliente_2.setText(_translate("reGI", "Aggiungi cliente"))
        self.btn_edit_cliente.setText(_translate("reGI", "Modifica cliente"))
        self.groupBox_3.setTitle(_translate("reGI", "Progetti"))
        self.btn_view_modelli.setText(_translate("reGI", "Visualizza progetti"))
        self.btn_agg_modello.setText(_translate("reGI", "Aggiungi progetto"))
        self.btn_edit_modello.setText(_translate("reGI", "Modifica progetto"))
        self.tab_clienti.setSortingEnabled(True)
        item = self.tab_clienti.horizontalHeaderItem(0)
        item.setText(_translate("reGI", "Cognome"))
        item = self.tab_clienti.horizontalHeaderItem(1)
        item.setText(_translate("reGI", "Nome"))
        item = self.tab_clienti.horizontalHeaderItem(2)
        item.setText(_translate("reGI", "Via"))
        item = self.tab_clienti.horizontalHeaderItem(3)
        item.setText(_translate("reGI", "Comune"))
        item = self.tab_clienti.horizontalHeaderItem(4)
        item.setText(_translate("reGI", "Tel. 1"))
        item = self.tab_clienti.horizontalHeaderItem(5)
        item.setText(_translate("reGI", "Tel. 2"))
        item = self.tab_clienti.horizontalHeaderItem(6)
        item.setText(_translate("reGI", "Email"))
        item = self.tab_clienti.horizontalHeaderItem(7)
        item.setText(_translate("reGI", "Cantiere"))
        self.label_2.setText(_translate("reGI", "Seleziona un cliente"))
        self.btn_canc_cliente.setText(_translate("reGI", "Elimina cliente"))
        self.btn_scegli_cliente.setText(_translate("reGI", "Scegli cliente"))
        self.btn_agg_cliente.setText(_translate("reGI", "Aggiungi cliente..."))
        self.label_23.setText(_translate("reGI", "Codice progetto"))
        self.label_24.setText(_translate("reGI", "Descrizione"))
        self.edit_note_descr.setPlaceholderText(_translate("reGI", "Inserisci delle note sul serramento richiesto dal cliente."))
        self.label_25.setText(_translate("reGI", "Note"))
        self.toolButton_9.setText(_translate("reGI", "..."))
        self.btn_nuovo_serr.setText(_translate("reGI", "Nuovo"))
        self.btn_dupl_serr.setText(_translate("reGI", "Duplica"))
        self.btn_canc_serr.setText(_translate("reGI", "Cancella"))
        self.edit_descr.setHtml(_translate("reGI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_26.setText(_translate("reGI", "Stampa:"))
        self.checkBox_2.setText(_translate("reGI", "modello 3D"))
        self.checkBox.setText(_translate("reGI", "modello 2D"))
        self.label_27.setText(_translate("reGI", "Posizione"))
        self.combo_materiale.setItemText(0, _translate("reGI", "Legno"))
        self.combo_materiale.setItemText(1, _translate("reGI", "L/A"))
        self.label_28.setText(_translate("reGI", "Materiale"))
        self.label_29.setText(_translate("reGI", "Verniciatura"))
        self.tree_progetti.headerItem().setText(0, _translate("reGI", "Codice/descrizione"))
        self.tree_progetti.headerItem().setText(1, _translate("reGI", "Dettagli"))
        __sortingEnabled = self.tree_progetti.isSortingEnabled()
        self.tree_progetti.setSortingEnabled(False)
        self.tree_progetti.topLevelItem(0).setText(0, _translate("reGI", "BA Sistema base"))
        self.tree_progetti.topLevelItem(0).child(0).setText(0, _translate("reGI", "SC Scorrevole complanare"))
        self.tree_progetti.topLevelItem(0).child(1).setText(0, _translate("reGI", "PF PortaFinestra"))
        self.tree_progetti.topLevelItem(0).child(2).setText(0, _translate("reGI", "FN Finestra"))
        self.tree_progetti.topLevelItem(0).child(3).setText(0, _translate("reGI", "AS Alzante scorrevole"))
        self.tree_progetti.topLevelItem(0).child(3).child(0).setText(0, _translate("reGI", "[HS5] Alzante Scorrevole 5 Ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(0).setText(1, _translate("reGI", "Alzante scorrevole semplice a cinque ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(1).setText(0, _translate("reGI", "[HS4] Alzante Scorrevole 4 Ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(1).setText(1, _translate("reGI", "Alzante scorrevole semplice a quattro ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(2).setText(0, _translate("reGI", "[HS3] Alzante Scorrevole 3 Ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(2).setText(1, _translate("reGI", "Alzante scorrevole semplice a tre ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(3).setText(0, _translate("reGI", "[HS2] Alzante Scorrevole 2 Ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(3).setText(1, _translate("reGI", "Alzante scorrevole semplice a due ante"))
        self.tree_progetti.topLevelItem(0).child(3).child(4).setText(0, _translate("reGI", "[HS1] Alzante Scorrevole 1 Anta"))
        self.tree_progetti.topLevelItem(0).child(3).child(4).setText(1, _translate("reGI", "Alzante scorrevole semplice a un\'anta"))
        self.tree_progetti.topLevelItem(1).setText(0, _translate("reGI", "LA Legno/alluminio"))
        self.tree_progetti.topLevelItem(1).child(0).setText(0, _translate("reGI", "PF Portafinestra"))
        self.tree_progetti.topLevelItem(1).child(1).setText(0, _translate("reGI", "FN Finestra"))
        self.tree_progetti.topLevelItem(2).setText(0, _translate("reGI", "SP Con sopraluce"))
        self.tree_progetti.setSortingEnabled(__sortingEnabled)
        self.label_30.setText(_translate("reGI", "Variante 3"))
        self.spin_l.setSuffix(_translate("reGI", " mm"))
        self.label_9.setText(_translate("reGI", "Lunghezza"))
        self.spin_h.setSuffix(_translate("reGI", " mm"))
        self.label_10.setText(_translate("reGI", "Altezza"))
        self.spin_s.setSuffix(_translate("reGI", " mm"))
        self.label_11.setText(_translate("reGI", "Spessore"))
        self.label_31.setText(_translate("reGI", "Note sulle varianti"))
        self.edit_note_varianti.setPlaceholderText(_translate("reGI", "Inserisci delle note sul materiale o sulla verniciatura richiesta dal cliente."))
        self.spin_pezzi.setSuffix(_translate("reGI", " pz."))
        self.label_12.setText(_translate("reGI", "N. pezzi"))
        self.label_32.setText(_translate("reGI", "Dimensioni"))
        self.label_33.setText(_translate("reGI", "Superficie"))
        self.label_34.setText(_translate("reGI", "Prezzo di listino unitario"))
        self.label_13.setText(_translate("reGI", "x"))
        self.radioButton.setText(_translate("reGI", "Sconto"))
        self.radioButton_2.setText(_translate("reGI", "Sconto percentuale"))
        self.label_35.setText(_translate("reGI", "Importo lordo"))
        self.label_37.setText(_translate("reGI", "IVA"))
        self.tab_dettaglio_totale.setTabText(self.tab_dettaglio_totale.indexOf(self.scheda_dettaglio), _translate("reGI", "Dettaglio"))
        self.label_36.setText(_translate("reGI", "Riepilogo serramenti"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("reGI", "Serramento"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("reGI", "Prezzo unitario lordo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("reGI", "N. pezzi"))
        self.tab_dettaglio_totale.setTabText(self.tab_dettaglio_totale.indexOf(self.scheda_totale), _translate("reGI", "Totale"))
        self.label.setText(_translate("reGI", "N. Preventivo"))
        self.label_5.setText(_translate("reGI", "Data"))
        self.label_6.setText(_translate("reGI", "Nome o ragione sociale"))
        self.label_7.setText(_translate("reGI", "Indirizzo"))
        self.label_8.setText(_translate("reGI", "Indirizzo cantiere"))
        self.label_14.setText(_translate("reGI", "Città e provincia"))
        self.btn_scegli_testo_in.setText(_translate("reGI", "..."))
        self.label_15.setText(_translate("reGI", "Testo iniziale"))
        self.btn_scegli_testo_out.setText(_translate("reGI", "..."))
        self.label_16.setText(_translate("reGI", "Testo finale"))
        self.label_17.setText(_translate("reGI", "Telefono 1"))
        self.label_18.setText(_translate("reGI", "Telefono 2"))
        self.label_19.setText(_translate("reGI", "Email"))
        self.label_20.setText(_translate("reGI", "Cliente associato"))
        self.label_21.setText(_translate("reGI", "N. pezzi provvisorio"))
        self.label_22.setText(_translate("reGI", "Totale provvisorio"))
        self.menuNuovo.setTitle(_translate("reGI", "File"))
        self.menuRecenti.setTitle(_translate("reGI", "Recenti"))
        self.menuNuovo_2.setTitle(_translate("reGI", "Nuovo..."))
        self.menuInserisci.setTitle(_translate("reGI", "Inserisci"))
        self.menuVista.setTitle(_translate("reGI", "Vista"))
        self.menuSeleziona_stile.setTitle(_translate("reGI", "Seleziona design"))
        self.menuAnteprima.setTitle(_translate("reGI", "Anteprima"))
        self.menuInfo.setTitle(_translate("reGI", "Info"))
        self.actionVersione.setText(_translate("reGI", "Versione..."))
        self.actionVerifica_aggiornamenti.setText(_translate("reGI", "Verifica aggiornamenti..."))
        self.actionApri.setText(_translate("reGI", "Apri..."))
        self.actionRecente_1.setText(_translate("reGI", "Recente 1"))
        self.actionRecente_2.setText(_translate("reGI", "Recente 2"))
        self.actionDa_zero.setText(_translate("reGI", "Preventivo da zero"))
        self.actionDa_precompilato.setText(_translate("reGI", "Preventivo da precompilato"))
        self.actionInfisso.setText(_translate("reGI", "Infisso..."))
        self.actionVisualizza_anteprima_di_stampa.setText(_translate("reGI", "Visualizza anteprima di stampa"))
        self.actionDefault.setText(_translate("reGI", "Default"))
        self.actionFusion.setText(_translate("reGI", "Fusion"))
        self.actionWindows.setText(_translate("reGI", "Windows"))
        self.actionWindows_Vista.setText(_translate("reGI", "Windows Vista"))
        self.actionSchermata_iniziale.setText(_translate("reGI", "Schermata iniziale"))
        self.actionAnagrafica_clienti.setText(_translate("reGI", "Anagrafica clienti"))
        self.actionLista_progetti.setText(_translate("reGI", "Lista progetti"))
        self.actionCliente.setText(_translate("reGI", "Cliente"))
        self.actionProgetto.setText(_translate("reGI", "Progetto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reGI = QtWidgets.QMainWindow()
    reGI.setWindowTitle("reGI a0.3.0") # non funge
    reGI.setWindowIcon(QtGui.QIcon("icon_0.png")) # funge
    ui = Ui_reGI()
    ui.setupUi(reGI)
    reGI.show()
    sys.exit(app.exec_())
    regi_db.db.close()
